services:
  mocks3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PULL_REPO: ${PULL_REPO:-docker.io}
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.org/simple}
    ports:
      - 8003:8003
