[tox]
envlist = py311, py312, py313

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313


[testenv]
package = skip
allowlist_externals = uv
setenv =
    UV_PROJECT_ENVIRONMENT = {envdir}
commands_pre =
    uv sync --frozen --python {envpython}
commands =
    coverage run {envbindir}/zope-testrunner -vvc1 --all --test-path ./src
    coverage xml
    coverage report -m
